var pairs = [

	{'id':1,
		'name':'tequila and tacos',
		"querystring":"tequila+nachos",
		'foodImg':'images/tacos.jpg',
		'drinkImg':'images/tequila.jpg'
	},
	{
		'id':2,
		'name':'wine and steak',
		"querystring":"wine+steak",
		'foodImg':'images/steak.jpg',
		'drinkImg':'images/wine.jpg',
	},
	{'id':3,
		'name':'beer and burger',
		"querystring":"pub+food",
		'foodImg':'images/burger.jpg',
		'drinkImg':'images/beer.jpg',
	},
	{'id':4,
		'name':'seafood and cider',
		"querystring":"fish",
		'foodImg':'images/fish.jpg',
		'drinkImg':'images/cider.jpg',
	},
	{'id':5,
		'name':'sushi and sake',
		"querystring":"sushi",
		'foodImg':'images/sushi.jpg',
		'drinkImg':'images/sake.jpg',
	},
	{'id':6,
		'name':'butter chicken and whiskey',
		"querystring":"indian",
		'foodImg':'images/curry.jpg',
		'drinkImg':'images/whiskey.jpg',
	},
	{'id':7,
		'name':'caesar and spaghetti',
		"querystring":"italian+cocktails+restaurant",
		'foodImg':'images/spaghetti.jpg',
		'drinkImg':'images/caesar.jpg',
	},
	{'id':8,
		'name':'sangria and nachos',
		"querystring":"nachos+sangria",
		'foodImg':'images/nachos.jpg',
		'drinkImg':'images/sangria.jpg',
	}
];
